const express = require('express');
const router = express.Router();
const { Appraisal } = require('../models/appraisal');
const { Employee } = require('../models/employee');

router.post('/', async (req, res) => {
    // console.log(req.body)
    // Extract the _id from the decoded token
    const {
        employeeid,
        year,
        classesTaught,
        totalClasses,
        totalScore1,
        paperEval,
        studentActivities,
        totalScore2,
        attendanceRecordFESE,
        meetingsConductedFESE,
        communicationFESE,
        counselingFESE,
        rankScore,
        coCurricularScore,
        percentageIncreaseScore,
        totalScoreFESE,
        attendanceRecordTE,
        meetingsConductedTE,
        communicationTE,
        counselingTE,
        adhonScore,
        otherScore,
        allClearScore,
        totalScoreTE,
        attendanceRecordBE,
        meetingsConductedBE,
        communicationBE,
        counselingBE,
        adhonCompleted,
        placementPercentage,
        batchEvaluation,
        actionTaken,
        totalScoreBE,
        latestResult,
        prevYearResult1,
        prevYearResult2,
        prevYearResult3,
        totalscore4,
        internalFeedback,
        externalFeedback,
        totalScore5,
        handwrittenNotes,
        otherContents,
        coPoPsoMapping,
        totalScore6,
        shortTerm7a,
        semester7a,
        academicYear7a,
        totalScore7a,
        shortTerm7b,
        semester7b,
        academicYear7b,
        totalScore7b,
        shortTerm7c,
        semester7c,
        academicYear7c,
        totalScore7c,
        internationalJournal,
        citation2022,
        totalScore8a,
        international,
        national,
        chapter,
        editorInternational,
        editorNational,
        researchPaper,
        book,
        totalScore8b1,
        innovativePedagogy,
        eContentDevelopment,
        totalScore8b2,
        phdGuidance,
        pgDissertation,
        completedResearchProjectMoreThan10Lakhs,
        completedResearchProjectLessThan10Lakhs,
        ongoingResearchProjectMoreThan10Lakhs,
        ongoingResearchProjectLessThan10Lakhs,
        inHouseProductDevelopment,
        consultancy,
        editorialBoardReviewer,
        paperPublishedWithIndustryPerson,
        totalScore8b3,
        internationalPatents,
        nationalPatents,
        copyrights,
        awards,
        totalScore8b4,
        intlAbroad,
        intlWithin,
        Innational,
        stateUni,
        totalScore8b5,
        sttpOrganized,
        sttpAttended,
        conferenceAttended,
        nptelCertification,
        academicQualification,
        mouWithIndustry,
        totalScore9,
        totalScoreformA,
        totalScoreformB,
        totalScore,
    } = req.body;



    try {
        // Find the employee by employeeId
        // console.log(employeeid)

        const employee = await Employee.findById(employeeid);

        if (!employee) {
            return res.status(404).json({ error: 'Employee not found.' });
        }
        // const existingAppraisal = await Appraisal.findOne({ employeeid, year });

        // if (existingAppraisal) {
        //     return res.status(400).json({ error: 'An appraisal entry already exists for the given employee and appraisal year.' });
        // }

        // Create the appraisal and associate it with the employee
        const appraisal = new Appraisal({
            employeeid,
            year,
            classesTaught,
            totalClasses,
            totalScore1,
            paperEval,
            studentActivities,
            totalScore2,
            attendanceRecordFESE,
            meetingsConductedFESE,
            communicationFESE,
            counselingFESE,
            rankScore,
            coCurricularScore,
            percentageIncreaseScore,
            totalScoreFESE,
            attendanceRecordTE,
            meetingsConductedTE,
            communicationTE,
            counselingTE,
            adhonScore,
            otherScore,
            allClearScore,
            totalScoreTE,
            attendanceRecordBE,
            meetingsConductedBE,
            communicationBE,
            counselingBE,
            adhonCompleted,
            placementPercentage,
            batchEvaluation,
            actionTaken,
            totalScoreBE,
            latestResult,
            prevYearResult1,
            prevYearResult2,
            prevYearResult3,
            totalscore4,
            internalFeedback,
            externalFeedback,
            totalScore5,
            handwrittenNotes,
            otherContents,
            coPoPsoMapping,
            totalScore6,
            shortTerm7a,
            semester7a,
            academicYear7a,
            totalScore7a,
            shortTerm7b,
            semester7b,
            academicYear7b,
            totalScore7b,
            shortTerm7c,
            semester7c,
            academicYear7c,
            totalScore7c,
            internationalJournal,
            citation2022,
            totalScore8a,
            international,
            national,
            chapter,
            editorInternational,
            editorNational,
            researchPaper,
            book,
            totalScore8b1,
            innovativePedagogy,
            eContentDevelopment,
            totalScore8b2,
            phdGuidance,
            pgDissertation,
            completedResearchProjectMoreThan10Lakhs,
            completedResearchProjectLessThan10Lakhs,
            ongoingResearchProjectMoreThan10Lakhs,
            ongoingResearchProjectLessThan10Lakhs,
            inHouseProductDevelopment,
            consultancy,
            editorialBoardReviewer,
            paperPublishedWithIndustryPerson,
            totalScore8b3,
            internationalPatents,
            nationalPatents,
            copyrights,
            awards,
            totalScore8b4,
            intlAbroad,
            intlWithin,
            Innational,
            stateUni,
            totalScore8b5,
            sttpOrganized,
            sttpAttended,
            conferenceAttended,
            nptelCertification,
            academicQualification,
            mouWithIndustry,
            totalScore9,
            totalScoreformA,
            totalScoreformB,
            totalScore


        });

        await appraisal.save();

        res.status(201).json({ message: 'Appraisal data saved successfully.' });
    } catch (error) {
        console.log(error)
        res.status(500).json({ error: 'An error occurred while saving the appraisal data.' });

    }
});

module.exports = router;
